spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?useSSL=true&useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234